### ISSUE TITLE
orderedlist conversion

### ISSUE THREAD

**Issue by peppobon** [transpect/hub2html#1]
It seems to me that the test on line 921should be reversed.
With the current `<xsl:when test="$redundant-overrides">` a naked orderedlist gets converted to a `<table class="BC_orderedlist">`, not as a standard ol, as it seems natural.

**Comment by polypunkt** [comment]
You are right. We assumed that there is always an @override attribute on a listitem. I will see to that. As well as to the created @class attribute names like "1" that are not valid. Thanks for reporting the issue.

**Comment by polypunkt** [comment]
Should work now.
